name: the global racontuer
favicon: null
layout_spectrum: 0.74396
typography_spectrum: 0.63198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.10426258179359138
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
